name: logistix_main
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Network & API
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^5.0.2
  http: ^1.2.0

  # Dependency Injection
  get_it: ^7.6.7

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utils
  logger: ^2.0.2+1
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  url_launcher: ^6.2.5
  jwt_decoder: ^2.0.1
  json_annotation: ^4.8.1

  # Map & Location
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  flutter_map_marker_popup: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/ 